### ISSUE TITLE
Exception: There is an open DataReader associated with this Connection which must be closed first

### ISSUE THREAD

**Issue by mbuchok** [Kaev/MySQL-To-CSharp#2]
First off, I like this little tool. Thanks.

In the main method there are some DataReader objects that throw the exception: **"There is an open DataReader associated with this Connection which must be closed first"**. Looks like this can be solved with using statements.

**Edit:** In case it helps, I installed with MySql.Data v8.0.20

**Comment by Kaev** [comment]
Hey, sorry, i didn't receive any mails for this issue and just saw it. I'm gonna fix that later today.

**Comment by Kaev** [comment]
Should be fixed now
